<?php

namespace App\Models\Dropshipping;

use App\Models\Catalogue\Shop;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * @property int $id
 * @property int $platform_id
 * @property int $shop_id
 * @property int $invoices_all
 * @property int $invoices_1y
 * @property int $invoices_1q
 * @property int $invoices_1m
 * @property int $invoices_1w
 * @property int $invoices_3d
 * @property int $invoices_ytd
 * @property int $invoices_qtd
 * @property int $invoices_mtd
 * @property int $invoices_wtd
 * @property int $invoices_tdy
 * @property int $invoices_lm
 * @property int $invoices_lw
 * @property int $invoices_ld
 * @property int $invoices_1y_ly
 * @property int $invoices_1q_ly
 * @property int $invoices_1m_ly
 * @property int $invoices_1w_ly
 * @property int $invoices_3d_ly
 * @property int $invoices_ytd_ly
 * @property int $invoices_qtd_ly
 * @property int $invoices_mtd_ly
 * @property int $invoices_wtd_ly
 * @property int $invoices_tdy_ly
 * @property int $invoices_lm_ly
 * @property int $invoices_lw_ly
 * @property int $invoices_ld_ly
 * @property int $invoices_py1
 * @property int $invoices_py2
 * @property int $invoices_py3
 * @property int $invoices_py4
 * @property int $invoices_py5
 * @property int $invoices_pq1
 * @property int $invoices_pq2
 * @property int $invoices_pq3
 * @property int $invoices_pq4
 * @property int $invoices_pq5
 * @property int $new_channels_all
 * @property int $new_channels_1y
 * @property int $new_channels_1q
 * @property int $new_channels_1m
 * @property int $new_channels_1w
 * @property int $new_channels_3d
 * @property int $new_channels_ytd
 * @property int $new_channels_qtd
 * @property int $new_channels_mtd
 * @property int $new_channels_wtd
 * @property int $new_channels_tdy
 * @property int $new_channels_lm
 * @property int $new_channels_lw
 * @property int $new_channels_ld
 * @property int $new_channels_1y_ly
 * @property int $new_channels_1q_ly
 * @property int $new_channels_1m_ly
 * @property int $new_channels_1w_ly
 * @property int $new_channels_3d_ly
 * @property int $new_channels_ytd_ly
 * @property int $new_channels_qtd_ly
 * @property int $new_channels_mtd_ly
 * @property int $new_channels_wtd_ly
 * @property int $new_channels_tdy_ly
 * @property int $new_channels_lm_ly
 * @property int $new_channels_lw_ly
 * @property int $new_channels_ld_ly
 * @property int $new_channels_py1
 * @property int $new_channels_py2
 * @property int $new_channels_py3
 * @property int $new_channels_py4
 * @property int $new_channels_py5
 * @property int $new_channels_pq1
 * @property int $new_channels_pq2
 * @property int $new_channels_pq3
 * @property int $new_channels_pq4
 * @property int $new_channels_pq5
 * @property int $new_customers_all
 * @property int $new_customers_1y
 * @property int $new_customers_1q
 * @property int $new_customers_1m
 * @property int $new_customers_1w
 * @property int $new_customers_3d
 * @property int $new_customers_ytd
 * @property int $new_customers_qtd
 * @property int $new_customers_mtd
 * @property int $new_customers_wtd
 * @property int $new_customers_tdy
 * @property int $new_customers_lm
 * @property int $new_customers_lw
 * @property int $new_customers_ld
 * @property int $new_customers_1y_ly
 * @property int $new_customers_1q_ly
 * @property int $new_customers_1m_ly
 * @property int $new_customers_1w_ly
 * @property int $new_customers_3d_ly
 * @property int $new_customers_ytd_ly
 * @property int $new_customers_qtd_ly
 * @property int $new_customers_mtd_ly
 * @property int $new_customers_wtd_ly
 * @property int $new_customers_tdy_ly
 * @property int $new_customers_lm_ly
 * @property int $new_customers_lw_ly
 * @property int $new_customers_ld_ly
 * @property int $new_customers_py1
 * @property int $new_customers_py2
 * @property int $new_customers_py3
 * @property int $new_customers_py4
 * @property int $new_customers_py5
 * @property int $new_customers_pq1
 * @property int $new_customers_pq2
 * @property int $new_customers_pq3
 * @property int $new_customers_pq4
 * @property int $new_customers_pq5
 * @property int $new_portfolios_all
 * @property int $new_portfolios_1y
 * @property int $new_portfolios_1q
 * @property int $new_portfolios_1m
 * @property int $new_portfolios_1w
 * @property int $new_portfolios_3d
 * @property int $new_portfolios_ytd
 * @property int $new_portfolios_qtd
 * @property int $new_portfolios_mtd
 * @property int $new_portfolios_wtd
 * @property int $new_portfolios_tdy
 * @property int $new_portfolios_lm
 * @property int $new_portfolios_lw
 * @property int $new_portfolios_ld
 * @property int $new_portfolios_1y_ly
 * @property int $new_portfolios_1q_ly
 * @property int $new_portfolios_1m_ly
 * @property int $new_portfolios_1w_ly
 * @property int $new_portfolios_3d_ly
 * @property int $new_portfolios_ytd_ly
 * @property int $new_portfolios_qtd_ly
 * @property int $new_portfolios_mtd_ly
 * @property int $new_portfolios_wtd_ly
 * @property int $new_portfolios_tdy_ly
 * @property int $new_portfolios_lm_ly
 * @property int $new_portfolios_lw_ly
 * @property int $new_portfolios_ld_ly
 * @property int $new_portfolios_py1
 * @property int $new_portfolios_py2
 * @property int $new_portfolios_py3
 * @property int $new_portfolios_py4
 * @property int $new_portfolios_py5
 * @property int $new_portfolios_pq1
 * @property int $new_portfolios_pq2
 * @property int $new_portfolios_pq3
 * @property int $new_portfolios_pq4
 * @property int $new_portfolios_pq5
 * @property int $new_customer_client_all
 * @property int $new_customer_client_1y
 * @property int $new_customer_client_1q
 * @property int $new_customer_client_1m
 * @property int $new_customer_client_1w
 * @property int $new_customer_client_3d
 * @property int $new_customer_client_ytd
 * @property int $new_customer_client_qtd
 * @property int $new_customer_client_mtd
 * @property int $new_customer_client_wtd
 * @property int $new_customer_client_tdy
 * @property int $new_customer_client_lm
 * @property int $new_customer_client_lw
 * @property int $new_customer_client_ld
 * @property int $new_customer_client_1y_ly
 * @property int $new_customer_client_1q_ly
 * @property int $new_customer_client_1m_ly
 * @property int $new_customer_client_1w_ly
 * @property int $new_customer_client_3d_ly
 * @property int $new_customer_client_ytd_ly
 * @property int $new_customer_client_qtd_ly
 * @property int $new_customer_client_mtd_ly
 * @property int $new_customer_client_wtd_ly
 * @property int $new_customer_client_tdy_ly
 * @property int $new_customer_client_lm_ly
 * @property int $new_customer_client_lw_ly
 * @property int $new_customer_client_ld_ly
 * @property int $new_customer_client_py1
 * @property int $new_customer_client_py2
 * @property int $new_customer_client_py3
 * @property int $new_customer_client_py4
 * @property int $new_customer_client_py5
 * @property int $new_customer_client_pq1
 * @property int $new_customer_client_pq2
 * @property int $new_customer_client_pq3
 * @property int $new_customer_client_pq4
 * @property int $new_customer_client_pq5
 * @property string $sales_all
 * @property string $sales_1y
 * @property string $sales_1q
 * @property string $sales_1m
 * @property string $sales_1w
 * @property string $sales_3d
 * @property string $sales_ytd
 * @property string $sales_qtd
 * @property string $sales_mtd
 * @property string $sales_wtd
 * @property string $sales_tdy
 * @property string $sales_lm
 * @property string $sales_lw
 * @property string $sales_ld
 * @property string $sales_1y_ly
 * @property string $sales_1q_ly
 * @property string $sales_1m_ly
 * @property string $sales_1w_ly
 * @property string $sales_3d_ly
 * @property string $sales_ytd_ly
 * @property string $sales_qtd_ly
 * @property string $sales_mtd_ly
 * @property string $sales_wtd_ly
 * @property string $sales_tdy_ly
 * @property string $sales_lm_ly
 * @property string $sales_lw_ly
 * @property string $sales_ld_ly
 * @property string $sales_py1
 * @property string $sales_py2
 * @property string $sales_py3
 * @property string $sales_py4
 * @property string $sales_py5
 * @property string $sales_pq1
 * @property string $sales_pq2
 * @property string $sales_pq3
 * @property string $sales_pq4
 * @property string $sales_pq5
 * @property string $sales_org_currency_all
 * @property string $sales_org_currency_1y
 * @property string $sales_org_currency_1q
 * @property string $sales_org_currency_1m
 * @property string $sales_org_currency_1w
 * @property string $sales_org_currency_3d
 * @property string $sales_org_currency_ytd
 * @property string $sales_org_currency_qtd
 * @property string $sales_org_currency_mtd
 * @property string $sales_org_currency_wtd
 * @property string $sales_org_currency_tdy
 * @property string $sales_org_currency_lm
 * @property string $sales_org_currency_lw
 * @property string $sales_org_currency_ld
 * @property string $sales_org_currency_1y_ly
 * @property string $sales_org_currency_1q_ly
 * @property string $sales_org_currency_1m_ly
 * @property string $sales_org_currency_1w_ly
 * @property string $sales_org_currency_3d_ly
 * @property string $sales_org_currency_ytd_ly
 * @property string $sales_org_currency_qtd_ly
 * @property string $sales_org_currency_mtd_ly
 * @property string $sales_org_currency_wtd_ly
 * @property string $sales_org_currency_tdy_ly
 * @property string $sales_org_currency_lm_ly
 * @property string $sales_org_currency_lw_ly
 * @property string $sales_org_currency_ld_ly
 * @property string $sales_org_currency_py1
 * @property string $sales_org_currency_py2
 * @property string $sales_org_currency_py3
 * @property string $sales_org_currency_py4
 * @property string $sales_org_currency_py5
 * @property string $sales_org_currency_pq1
 * @property string $sales_org_currency_pq2
 * @property string $sales_org_currency_pq3
 * @property string $sales_org_currency_pq4
 * @property string $sales_org_currency_pq5
 * @property string $sales_grp_currency_all
 * @property string $sales_grp_currency_1y
 * @property string $sales_grp_currency_1q
 * @property string $sales_grp_currency_1m
 * @property string $sales_grp_currency_1w
 * @property string $sales_grp_currency_3d
 * @property string $sales_grp_currency_ytd
 * @property string $sales_grp_currency_qtd
 * @property string $sales_grp_currency_mtd
 * @property string $sales_grp_currency_wtd
 * @property string $sales_grp_currency_tdy
 * @property string $sales_grp_currency_lm
 * @property string $sales_grp_currency_lw
 * @property string $sales_grp_currency_ld
 * @property string $sales_grp_currency_1y_ly
 * @property string $sales_grp_currency_1q_ly
 * @property string $sales_grp_currency_1m_ly
 * @property string $sales_grp_currency_1w_ly
 * @property string $sales_grp_currency_3d_ly
 * @property string $sales_grp_currency_ytd_ly
 * @property string $sales_grp_currency_qtd_ly
 * @property string $sales_grp_currency_mtd_ly
 * @property string $sales_grp_currency_wtd_ly
 * @property string $sales_grp_currency_tdy_ly
 * @property string $sales_grp_currency_lm_ly
 * @property string $sales_grp_currency_lw_ly
 * @property string $sales_grp_currency_ld_ly
 * @property string $sales_grp_currency_py1
 * @property string $sales_grp_currency_py2
 * @property string $sales_grp_currency_py3
 * @property string $sales_grp_currency_py4
 * @property string $sales_grp_currency_py5
 * @property string $sales_grp_currency_pq1
 * @property string $sales_grp_currency_pq2
 * @property string $sales_grp_currency_pq3
 * @property string $sales_grp_currency_pq4
 * @property string $sales_grp_currency_pq5
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder<static>|PlatformShopSalesIntervals newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|PlatformShopSalesIntervals newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|PlatformShopSalesIntervals query()
 * @mixin \Eloquent
 */
class PlatformShopSalesIntervals extends Model
{
    protected $guarded = [];

    public function platform(): BelongsTo
    {
        return $this->belongsTo(Platform::class);
    }

    public function shop(): BelongsTo
    {
        return $this->belongsTo(Shop::class);
    }
}
