#!/usr/bin/env bash
#
# Render the tracked devops/ configs onto a server, validate, and reload.
#
# Scope: CONFIG ONLY. This does not install packages — php8.4, nginx, haproxy,
# varnish and supervisor must already be present. Package install is a rare
# one-time step done by hand; the recurring pain this solves is config drift.
#
# Role: production app server. Per host differences (program names, Octane
# sizing) come from APP_HOST/OCTANE_* in server.env, so the same tree renders
# boro or helio. Staging still differs in backend IPs — review before running.
#
# Usage (as root, on the target box, from a repo checkout):
#     sudo ./devops/setup-server.sh              # apply
#     sudo DRY_RUN=1 ./devops/setup-server.sh    # preview, touch nothing
#
# Secrets come from devops/server.env (gitignored) — copy server.env.example.
#
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEVOPS="$REPO_DIR/devops"
ENV_FILE="${ENV_FILE:-$DEVOPS/server.env}"
DRY_RUN="${DRY_RUN:-0}"

[[ $EUID -eq 0 ]] || { echo "must run as root (sudo)"; exit 1; }
[[ -f "$ENV_FILE" ]] || { echo "missing $ENV_FILE — copy server.env.example and fill it in"; exit 1; }
# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

# required values — fail early if unset
: "${HAPROXY_STATS_USER:?set it in $ENV_FILE}"
: "${HAPROXY_STATS_PASSWORD:?set it in $ENV_FILE}"
: "${VARNISH_HOST_BORO:?set it in $ENV_FILE}"
: "${VARNISH_HOST_HELIO:?set it in $ENV_FILE}"
: "${APP_HOST:?set it in $ENV_FILE — boro or helio}"
: "${OCTANE_WORKERS:?set it in $ENV_FILE}"
: "${OCTANE_MAX_REQUESTS:?set it in $ENV_FILE}"
INSTALL_SCHEDULER="${INSTALL_SCHEDULER:-0}"

# place <src> <dst> [mode]
# Substitutes every {{VAR}} from the environment (dies on an unset placeholder,
# which catches a missed secret), then installs — or previews under DRY_RUN.
# Files without any {{VAR}} pass through untouched, so this handles both.
place() {
  local src=$1 dst=$2 mode=${3:-644} tmp
  tmp=$(mktemp)
  perl -0pe 's/\{\{(\w+)\}\}/ exists $ENV{$1} ? $ENV{$1} : die "unset placeholder {{$1}} in '"$src"'\n" /ge' "$src" > "$tmp"
  if [[ $DRY_RUN == 1 ]]; then
    echo "  [dry-run] would write $dst (mode $mode)"
  else
    install -D -m "$mode" "$tmp" "$dst"
    echo "  -> $dst"
  fi
  rm -f "$tmp"
}

echo "haproxy:"
place "$DEVOPS/haproxy/haproxy.cfg"        /etc/haproxy/haproxy.cfg
place "$DEVOPS/haproxy/CF_ips.lst"         /etc/haproxy/CF_ips.lst
place "$DEVOPS/haproxy/facebook-bots.lst"  /etc/haproxy/facebook-bots.lst

echo "nginx:"
place "$DEVOPS/nginx/aiku-octane-production.conf" /etc/nginx/sites-available/aiku-octane-production.conf
if [[ $DRY_RUN != 1 ]]; then
  ln -sfn /etc/nginx/sites-available/aiku-octane-production.conf \
          /etc/nginx/sites-enabled/aiku-octane-production.conf
fi

echo "supervisor:"
# Staging configs live in the same directory but name the staging user and its
# /home/staging paths, and aiku-staging-inertia-ssr.conf declares the same
# program name as the production one — installing them here would give a
# production box a duplicate program pointing at a home that does not exist.
for f in "$DEVOPS"/supervisor/aiku-*.conf; do
  case "$(basename "$f")" in
    aiku-staging-*) continue ;;
  esac
  place "$f" "/etc/supervisor/conf.d/$(basename "$f")"
done
# Debian ships supervisor.service with KillMode=process, so a stop that outruns
# systemd's timeout SIGKILLs supervisord alone and reparents the horizon master
# to init; the next supervisord then starts a second one and every queue runs
# twice. TimeoutStopSec is deliberately above the programs' stopwaitsecs so
# workers still get their full drain window and systemd never cuts in first.
if [[ -f /lib/systemd/system/supervisor.service || -f /etc/systemd/system/supervisor.service ]]; then
  place "$DEVOPS/systemd/supervisor.conf" /etc/systemd/system/supervisor.service.d/aiku.conf
else
  echo "  skipped drop-in (no supervisor unit on this host)"
fi

echo "varnish:"
place "$DEVOPS/varnish/default.vcl" /etc/varnish/default.vcl

echo "sysctl:"
place "$DEVOPS/sysctl/99-aiku.conf" /etc/sysctl.d/99-aiku.conf
if [[ $DRY_RUN != 1 ]]; then
  sysctl -q --load /etc/sysctl.d/99-aiku.conf
fi

echo "github runner:"
# Drop-in, not a full unit: the unit itself is generated by the runner's own
# svc.sh install and gets rewritten on every runner upgrade. Without this the
# service stays `failed` after an OOM and CI silently stops running, and the
# stock KillMode=process orphans Runner.Listener on every restart until two
# listeners race over one _work dir and checkout dies on a missing _temp file.
shopt -s nullglob
runner_units=(/etc/systemd/system/actions.runner.*.service)
shopt -u nullglob
if [[ ${#runner_units[@]} -eq 0 ]]; then
  echo "  skipped (no actions.runner unit on this host)"
else
  for unit in "${runner_units[@]}"; do
    place "$DEVOPS/systemd/actions-runner.conf" "$unit.d/aiku.conf"
  done
fi

echo "cron:"
if [[ $INSTALL_SCHEDULER == 1 ]]; then
  if [[ $DRY_RUN == 1 ]]; then
    echo "  [dry-run] would install scheduler crontab for user aiku"
  else
    crontab -u aiku "$DEVOPS/cron/crontab"
    echo "  -> scheduler crontab installed for aiku"
  fi
else
  echo "  skipped (INSTALL_SCHEDULER=0 — scheduler runs on one host only)"
fi

if [[ $APP_HOST == boro ]]; then
  if [[ $DRY_RUN == 1 ]]; then
    echo "  [dry-run] would install /etc/cron.d/pg-freeze-sweep"
  else
    install -m 644 "$DEVOPS/cron/pg-freeze-sweep" /etc/cron.d/pg-freeze-sweep
    echo "  -> pg-freeze-sweep installed (primary DB host)"
  fi
else
  echo "  pg-freeze-sweep skipped (primary DB host only)"
fi

echo "postgres:"
case $APP_HOST in
  boro)  pg_conf="boro-production.conf" ;;
  helio) pg_conf="helio-replica.conf" ;;
  *)     pg_conf="" ;;
esac
if [[ -n $pg_conf ]]; then
  place "$DEVOPS/postgres/$pg_conf" "/etc/postgresql/18/main/conf.d/99-$APP_HOST.conf"
  echo "  NOTE: postgresql.auto.conf (ALTER SYSTEM) overrides conf.d — on an"
  echo "  existing cluster verify with: psql -c 'select name,setting,source from pg_settings'"
else
  echo "  skipped (no postgres conf for $APP_HOST)"
fi

if [[ $DRY_RUN == 1 ]]; then
  echo "dry-run complete — nothing written."
  exit 0
fi

echo "validating + reloading:"
nginx -t && systemctl reload nginx
haproxy -c -f /etc/haproxy/haproxy.cfg && systemctl reload haproxy
supervisorctl reread && supervisorctl update
systemctl daemon-reload
# Varnish reload semantics vary by install (varnishreload vs restart); leave it
# to the operator so a bad VCL can't take the cache down unattended.
echo "varnish: default.vcl placed — reload it manually (varnishreload or restart)."

echo "done."
