proxy_cache_path /var/cache/nginx/imgproxy/production levels=1:2 keys_zone=AIKU_MEDIA:64m max_size=80g inactive=7d use_temp_path=off;
server {
        listen 127.0.0.1:{{IMGPROXY_NGINX_PORT}};
        server_name media.aiku.io;
        location / {
                proxy_cache AIKU_MEDIA;
                proxy_pass http://{{IMGPROXY_PUBLISH}};
        }
}
