;etc/supervisor/aiku-inertia-ssr.conf
[program:inertia-ssr-production]
process_name=%(program_name)s
command=/usr/bin/php8.4 /home/aiku/aiku/anchor/octane/artisan inertia:start-ssr --runtime bun
autostart=true
autorestart=true
user=aiku
redirect_stderr=true
stdout_logfile=/home/aiku/logs/inertia_ssr.log
stopasgroup=true
killasgroup=true
stopwaitsecs=5
