;etc/supervisor/aiku-owl.conf
[program:aiku-owl]
process_name=%(program_name)s
command=/usr/bin/php8.4 /home/aiku/aiku/anchor/octane/artisan nightowl:agent
autorestart=true
user=aiku
redirect_stderr=true
stdout_logfile=/home/aiku/logs/owl.log
stopwaitsecs=3600
