;etc/supervisor/conf/aiku-production-horizon.conf
[program:horizon-aiku-production-boro]
process_name=%(program_name)s
command=/usr/bin/php8.4 /home/aiku/aiku/current/artisan horizon --no-interaction
autostart=true
autorestart=true
user=aiku
redirect_stderr=true
stdout_logfile=/home/aiku/logs/horizon.log
stopwaitsecs=3600
