;etc/supervisor/aiku-production-octane.conf
[program:aiku-octane-production_{{APP_HOST}}]
process_name=%(program_name)s
command=/usr/bin/php8.4 /home/aiku/aiku/anchor/octane/artisan octane:start -q --workers={{OCTANE_WORKERS}} --max-requests={{OCTANE_MAX_REQUESTS}}
autostart=true
autorestart=true
user=aiku
redirect_stderr=true
stdout_logfile=/home/aiku/logs/supervisor-production-octane.log
stopwaitsecs=3600
