;etc/supervisor/aiku-production-octane.conf
[program:aiku-octane-production_boro]
process_name=%(program_name)s
command=/usr/bin/php8.4 /home/aiku/aiku/anchor/octane/artisan octane:start -q --workers=48 --max-requests=400
autostart=true
autorestart=true
user=aiku
redirect_stderr=true
stdout_logfile=/home/aiku/logs/supervisor-production-octane.log
stopwaitsecs=3600
