[program:aiku-horizon]
process_name=%(program_name)s
command=/usr/bin/php8.4 -d newrelic.enabled=true -d newrelic.appname="{{write here new relic app name}}-horizon" -d newrelic.daemon.address="{{write here new relic daemon address}}" -d newrelic.license="{{write here new relic license key}}" -d newrelic.labels="environment:{{write here app env}};process:horizon" -d newrelic.background_job=true -d newrelic.daemon.app_connect_timeout=5s {{write here the user home dir}}/aiku/anchor/octane/artisan horizon --no-interaction
autostart=true
autorestart=true
user={{ write here the user}}
redirect_stderr=true
stdout_logfile={{write here the user home dir}}/logs/supervisor-horizon.log
stopwaitsecs=3600
