[program:aiku-octane-production-replica_{{APP_HOST}}]
process_name=%(program_name)s
command=/usr/bin/php8.4 /home/aiku/aiku/anchor/octane/artisan octane:start -q --port=8001 --rpc-port=6003 --rr-config=/home/aiku/rr-octane-replica.yaml --workers={{OCTANE_REPLICA_WORKERS}} --max-requests={{OCTANE_MAX_REQUESTS}}
environment=PROCESS_DB_READ_HOSTS="127.0.0.1",PROCESS_OCTANE_STATE_FILE="logs/{{APP_HOST}}-replica-octane-server-state.json"
autostart=true
autorestart=true
user=aiku
redirect_stderr=true
stdout_logfile=/home/aiku/logs/supervisor-production-octane-replica.log
stopwaitsecs=3600
