[program:soketi]
command=/opt/node-v18.20.8-linux-x64/bin/node /opt/soketi/bin/soketi start --config=/home/aiku/soketi/soketi-conf.json
environment=PATH="/opt/node-v18.20.8-linux-x64/bin:/usr/bin:/bin"
autostart=true
autorestart=true
user=aiku
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/home/aiku/soketi/soketi.log
stopwaitsecs=60
stopsignal=INT
minfds=10240
