bind 127.0.0.1 10.0.0.3
port 6380
protected-mode no
tcp-keepalive 300
timeout 0
daemonize no
supervised systemd
pidfile /run/redis-queue/redis-server.pid
logfile /var/log/redis/redis-server-queue.log
databases 16
dir /var/lib/redis/queue
dbfilename queue.rdb
save 900 1 300 10 60 10000
stop-writes-on-bgsave-error no
appendonly no
maxmemory 20gb
maxmemory-policy noeviction
