<?php

use App\Actions\Chat\Agent\UI\ShowShopAgents;
use App\Actions\Chat\ChatSession\ExportChatConversations;
use App\Actions\Chat\ChatSession\GetChatDashboardVisitors;
use App\Actions\Chat\ChatSession\UI\ShowOrgChatConversation;
use App\Actions\Chat\ChatSession\UI\ShowOrgChatInbox;
use App\Actions\Chat\ChatSession\UI\ShowShopChatConversations;
use App\Actions\Chat\ChatSession\UI\ShowShopChatDashboard;
use App\Actions\Chat\PhoneCall\UI\ShowOrgChatPhoneCalls;
use App\Actions\Chat\UI\ShowChatSettings;
use App\Actions\Chat\UpdateShopOutOfHoursMessage;
use App\Actions\Chat\Whatsapp\GetWhatsappPhoneNumberStatus;
use App\Actions\Chat\Whatsapp\GetWhatsappSubscribedApps;
use App\Actions\Chat\Whatsapp\RegisterWhatsappPhoneNumber;
use App\Actions\Chat\Whatsapp\RequestWhatsappPhoneNumberCode;
use App\Actions\Chat\Whatsapp\SubscribeWhatsappApp;
use App\Actions\Chat\Whatsapp\VerifyWhatsappPhoneNumberCode;
use App\Actions\Chat\Whatsapp\Templates\DeleteWhatsappMessageTemplate;
use App\Actions\Chat\Whatsapp\Templates\RefreshWhatsappMessageTemplate;
use App\Actions\Chat\Whatsapp\Templates\StoreWhatsappMessageTemplate;
use App\Actions\Chat\Whatsapp\Templates\StoreWhatsappTemplateDraft;
use App\Actions\Chat\Whatsapp\Templates\SubmitWhatsappTemplateDraft;
use App\Actions\Chat\Whatsapp\Templates\SyncWhatsappMessageTemplates;
use App\Actions\Chat\Whatsapp\Templates\UI\CreateWhatsappMessageTemplate;
use App\Actions\Chat\Whatsapp\Templates\UI\EditWhatsappMessageTemplate;
use App\Actions\Chat\Whatsapp\Templates\UpdateWhatsappMessageTemplate;
use App\Actions\Chat\Whatsapp\Templates\UpdateWhatsappTemplateHeaderMedia;
use App\Actions\Chat\Whatsapp\Templates\UpdateWhatsappTemplateTags;
use App\Actions\Chat\Whatsapp\Templates\UI\IndexWhatsappMessageTemplates;
use Illuminate\Support\Facades\Route;

Route::get('/reports', ShowShopChatDashboard::class)->name('reports');
Route::get('/inbox', [ShowOrgChatInbox::class, 'inShop'])->name('inbox');
Route::get('/supervision', [ShowOrgChatInbox::class, 'supervisionInShop'])->name('supervision');
Route::get('/dashboard-visitors', [GetChatDashboardVisitors::class, 'inShop'])->name('dashboard-visitors');
Route::get('/agents', ShowShopAgents::class)->name('agents.show');
Route::get('/phone-calls', [ShowOrgChatPhoneCalls::class, 'inShop'])->name('phone_calls.index');
Route::get('/settings', [ShowChatSettings::class, 'inShop'])->name('settings');
Route::patch('/settings/out-of-hours-message', UpdateShopOutOfHoursMessage::class)->name('settings.out_of_hours_message.update');
Route::get('/conversations/export', [ExportChatConversations::class, 'inShop'])->name('conversations.export');
Route::get('/conversations', ShowShopChatConversations::class)->name('conversations.show');
Route::get('/conversations/{chatSession}', [ShowOrgChatConversation::class, 'inShop'])->name('conversations.detail');
Route::get('/whatsapp-templates', [IndexWhatsappMessageTemplates::class, 'inShop'])->name('whatsapp_templates.index');
Route::get('/whatsapp-templates/create', CreateWhatsappMessageTemplate::class)->name('whatsapp_templates.create');
Route::post('/whatsapp-templates', StoreWhatsappMessageTemplate::class)->name('whatsapp_templates.store');
Route::post('/whatsapp-templates/draft', StoreWhatsappTemplateDraft::class)->name('whatsapp_templates.draft.store');
Route::get('/whatsapp-templates/{metaMessageTemplate}/draft', [CreateWhatsappMessageTemplate::class, 'inDraft'])->name('whatsapp_templates.draft.edit');
Route::get('/whatsapp-templates/{metaMessageTemplate}/language', [CreateWhatsappMessageTemplate::class, 'inLanguage'])->name('whatsapp_templates.language');
Route::post('/whatsapp-templates/{metaMessageTemplate}/draft', [StoreWhatsappTemplateDraft::class, 'inTemplate'])->name('whatsapp_templates.draft.update');
Route::post('/whatsapp-templates/{metaMessageTemplate}/submit', [SubmitWhatsappTemplateDraft::class, 'inTemplate'])->name('whatsapp_templates.draft.submit');
Route::get('/whatsapp-templates/{metaMessageTemplate}/edit', EditWhatsappMessageTemplate::class)->name('whatsapp_templates.edit');
Route::patch('/whatsapp-templates/{metaMessageTemplate}', UpdateWhatsappMessageTemplate::class)->name('whatsapp_templates.update');
Route::post('/whatsapp-templates/{metaMessageTemplate}/header-media', UpdateWhatsappTemplateHeaderMedia::class)->name('whatsapp_templates.header_media');
Route::patch('/whatsapp-templates/{metaMessageTemplate}/variables', UpdateWhatsappTemplateTags::class)->name('whatsapp_templates.variables');
Route::delete('/whatsapp-templates/{metaMessageTemplate}', DeleteWhatsappMessageTemplate::class)->name('whatsapp_templates.delete');
Route::post('/whatsapp-templates/{metaMessageTemplate}/refresh', RefreshWhatsappMessageTemplate::class)->name('whatsapp_templates.refresh');
Route::post('/whatsapp-templates/sync', SyncWhatsappMessageTemplates::class)->name('whatsapp_templates.sync');

Route::post('/whatsapp-phone/status', GetWhatsappPhoneNumberStatus::class)->name('whatsapp_phone.status');
Route::post('/whatsapp-phone/request-code', RequestWhatsappPhoneNumberCode::class)->name('whatsapp_phone.request_code');
Route::post('/whatsapp-phone/verify-code', VerifyWhatsappPhoneNumberCode::class)->name('whatsapp_phone.verify_code');
Route::post('/whatsapp-phone/register', RegisterWhatsappPhoneNumber::class)->name('whatsapp_phone.register');

Route::post('/whatsapp-app/subscribed', GetWhatsappSubscribedApps::class)->name('whatsapp_app.subscribed');
Route::post('/whatsapp-app/subscribe', SubscribeWhatsappApp::class)->name('whatsapp_app.subscribe');
