listen_addresses = 'localhost,10.0.0.1'
max_connections = 1000
max_worker_processes = 51
max_locks_per_transaction = 1024
max_wal_senders = 10
max_prepared_transactions = 0
shared_buffers = 16GB
effective_cache_size = 64GB
work_mem = 12MB
maintenance_work_mem = 2GB
huge_pages = try
random_page_cost = 1.1
effective_io_concurrency = 256
jit = off
max_wal_size = 32GB
checkpoint_timeout = 30min
wal_compression = lz4
hot_standby = on
hot_standby_feedback = on
max_standby_streaming_delay = 30s
shared_preload_libraries = 'pg_stat_statements'
timezone = 'UTC'
log_timezone = 'UTC'
