<?php

/*
 * Author: Raul Perusquia <raul@inikoo.com>
 * Created: Sat, 12 Apr 2025 15:33:25 Malaysia Time, Kuala Lumpur, Malaysia
 * Copyright (c) 2025, Raul A Perusquia Flores
 */

namespace App\Models;

use App\Models\Goods\Stock;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 *
 *
 * @property int $id
 * @property int $stock_id
 * @property string $revenue_grp_currency_all
 * @property string $revenue_grp_currency_1y
 * @property string $revenue_grp_currency_1q
 * @property string $revenue_grp_currency_1m
 * @property string $revenue_grp_currency_1w
 * @property string $revenue_grp_currency_3d
 * @property string $revenue_grp_currency_ytd
 * @property string $revenue_grp_currency_qtd
 * @property string $revenue_grp_currency_mtd
 * @property string $revenue_grp_currency_wtd
 * @property string $revenue_grp_currency_tdy
 * @property string $revenue_grp_currency_lm
 * @property string $revenue_grp_currency_lw
 * @property string $revenue_grp_currency_ld
 * @property string $revenue_grp_currency_1y_ly
 * @property string $revenue_grp_currency_1q_ly
 * @property string $revenue_grp_currency_1m_ly
 * @property string $revenue_grp_currency_1w_ly
 * @property string $revenue_grp_currency_3d_ly
 * @property string $revenue_grp_currency_ytd_ly
 * @property string $revenue_grp_currency_qtd_ly
 * @property string $revenue_grp_currency_mtd_ly
 * @property string $revenue_grp_currency_wtd_ly
 * @property string $revenue_grp_currency_tdy_ly
 * @property string $revenue_grp_currency_lm_ly
 * @property string $revenue_grp_currency_lw_ly
 * @property string $revenue_grp_currency_ld_ly
 * @property string $revenue_grp_currency_py1
 * @property string $revenue_grp_currency_py2
 * @property string $revenue_grp_currency_py3
 * @property string $revenue_grp_currency_py4
 * @property string $revenue_grp_currency_py5
 * @property string $revenue_grp_currency_pq1
 * @property string $revenue_grp_currency_pq2
 * @property string $revenue_grp_currency_pq3
 * @property string $revenue_grp_currency_pq4
 * @property string $revenue_grp_currency_pq5
 * @property string $profit_grp_currency_all
 * @property string $profit_grp_currency_1y
 * @property string $profit_grp_currency_1q
 * @property string $profit_grp_currency_1m
 * @property string $profit_grp_currency_1w
 * @property string $profit_grp_currency_3d
 * @property string $profit_grp_currency_ytd
 * @property string $profit_grp_currency_qtd
 * @property string $profit_grp_currency_mtd
 * @property string $profit_grp_currency_wtd
 * @property string $profit_grp_currency_tdy
 * @property string $profit_grp_currency_lm
 * @property string $profit_grp_currency_lw
 * @property string $profit_grp_currency_ld
 * @property string $profit_grp_currency_1y_ly
 * @property string $profit_grp_currency_1q_ly
 * @property string $profit_grp_currency_1m_ly
 * @property string $profit_grp_currency_1w_ly
 * @property string $profit_grp_currency_3d_ly
 * @property string $profit_grp_currency_ytd_ly
 * @property string $profit_grp_currency_qtd_ly
 * @property string $profit_grp_currency_mtd_ly
 * @property string $profit_grp_currency_wtd_ly
 * @property string $profit_grp_currency_tdy_ly
 * @property string $profit_grp_currency_lm_ly
 * @property string $profit_grp_currency_lw_ly
 * @property string $profit_grp_currency_ld_ly
 * @property string $profit_grp_currency_py1
 * @property string $profit_grp_currency_py2
 * @property string $profit_grp_currency_py3
 * @property string $profit_grp_currency_py4
 * @property string $profit_grp_currency_py5
 * @property string $profit_grp_currency_pq1
 * @property string $profit_grp_currency_pq2
 * @property string $profit_grp_currency_pq3
 * @property string $profit_grp_currency_pq4
 * @property string $profit_grp_currency_pq5
 * @property string|null $revenue_data_all
 * @property string|null $revenue_data_1y
 * @property string|null $revenue_data_1q
 * @property string|null $revenue_data_1m
 * @property string|null $revenue_data_1w
 * @property string|null $revenue_data_3d
 * @property string|null $revenue_data_ytd
 * @property string|null $revenue_data_qtd
 * @property string|null $revenue_data_mtd
 * @property string|null $revenue_data_wtd
 * @property string|null $revenue_data_tdy
 * @property string|null $revenue_data_lm
 * @property string|null $revenue_data_lw
 * @property string|null $revenue_data_ld
 * @property string|null $revenue_data_1y_ly
 * @property string|null $revenue_data_1q_ly
 * @property string|null $revenue_data_1m_ly
 * @property string|null $revenue_data_1w_ly
 * @property string|null $revenue_data_3d_ly
 * @property string|null $revenue_data_ytd_ly
 * @property string|null $revenue_data_qtd_ly
 * @property string|null $revenue_data_mtd_ly
 * @property string|null $revenue_data_wtd_ly
 * @property string|null $revenue_data_tdy_ly
 * @property string|null $revenue_data_lm_ly
 * @property string|null $revenue_data_lw_ly
 * @property string|null $revenue_data_ld_ly
 * @property string|null $revenue_data_py1
 * @property string|null $revenue_data_py2
 * @property string|null $revenue_data_py3
 * @property string|null $revenue_data_py4
 * @property string|null $revenue_data_py5
 * @property string|null $revenue_data_pq1
 * @property string|null $revenue_data_pq2
 * @property string|null $revenue_data_pq3
 * @property string|null $revenue_data_pq4
 * @property string|null $revenue_data_pq5
 * @property int $number_invoices_all
 * @property int $number_invoices_1y
 * @property int $number_invoices_1q
 * @property int $number_invoices_1m
 * @property int $number_invoices_1w
 * @property int $number_invoices_3d
 * @property int $number_invoices_ytd
 * @property int $number_invoices_qtd
 * @property int $number_invoices_mtd
 * @property int $number_invoices_wtd
 * @property int $number_invoices_tdy
 * @property int $number_invoices_lm
 * @property int $number_invoices_lw
 * @property int $number_invoices_ld
 * @property int $number_invoices_1y_ly
 * @property int $number_invoices_1q_ly
 * @property int $number_invoices_1m_ly
 * @property int $number_invoices_1w_ly
 * @property int $number_invoices_3d_ly
 * @property int $number_invoices_ytd_ly
 * @property int $number_invoices_qtd_ly
 * @property int $number_invoices_mtd_ly
 * @property int $number_invoices_wtd_ly
 * @property int $number_invoices_tdy_ly
 * @property int $number_invoices_lm_ly
 * @property int $number_invoices_lw_ly
 * @property int $number_invoices_ld_ly
 * @property int $number_invoices_py1
 * @property int $number_invoices_py2
 * @property int $number_invoices_py3
 * @property int $number_invoices_py4
 * @property int $number_invoices_py5
 * @property int $number_invoices_pq1
 * @property int $number_invoices_pq2
 * @property int $number_invoices_pq3
 * @property int $number_invoices_pq4
 * @property int $number_invoices_pq5
 * @property int $number_customers_all
 * @property int $number_customers_1y
 * @property int $number_customers_1q
 * @property int $number_customers_1m
 * @property int $number_customers_1w
 * @property int $number_customers_3d
 * @property int $number_customers_ytd
 * @property int $number_customers_qtd
 * @property int $number_customers_mtd
 * @property int $number_customers_wtd
 * @property int $number_customers_tdy
 * @property int $number_customers_lm
 * @property int $number_customers_lw
 * @property int $number_customers_ld
 * @property int $number_customers_1y_ly
 * @property int $number_customers_1q_ly
 * @property int $number_customers_1m_ly
 * @property int $number_customers_1w_ly
 * @property int $number_customers_3d_ly
 * @property int $number_customers_ytd_ly
 * @property int $number_customers_qtd_ly
 * @property int $number_customers_mtd_ly
 * @property int $number_customers_wtd_ly
 * @property int $number_customers_tdy_ly
 * @property int $number_customers_lm_ly
 * @property int $number_customers_lw_ly
 * @property int $number_customers_ld_ly
 * @property int $number_customers_py1
 * @property int $number_customers_py2
 * @property int $number_customers_py3
 * @property int $number_customers_py4
 * @property int $number_customers_py5
 * @property int $number_customers_pq1
 * @property int $number_customers_pq2
 * @property int $number_customers_pq3
 * @property int $number_customers_pq4
 * @property int $number_customers_pq5
 * @property string $revenue_b2b_grp_currency_all
 * @property string $revenue_b2b_grp_currency_1y
 * @property string $revenue_b2b_grp_currency_1q
 * @property string $revenue_b2b_grp_currency_1m
 * @property string $revenue_b2b_grp_currency_1w
 * @property string $revenue_b2b_grp_currency_3d
 * @property string $revenue_b2b_grp_currency_ytd
 * @property string $revenue_b2b_grp_currency_qtd
 * @property string $revenue_b2b_grp_currency_mtd
 * @property string $revenue_b2b_grp_currency_wtd
 * @property string $revenue_b2b_grp_currency_tdy
 * @property string $revenue_b2b_grp_currency_lm
 * @property string $revenue_b2b_grp_currency_lw
 * @property string $revenue_b2b_grp_currency_ld
 * @property string $revenue_b2b_grp_currency_1y_ly
 * @property string $revenue_b2b_grp_currency_1q_ly
 * @property string $revenue_b2b_grp_currency_1m_ly
 * @property string $revenue_b2b_grp_currency_1w_ly
 * @property string $revenue_b2b_grp_currency_3d_ly
 * @property string $revenue_b2b_grp_currency_ytd_ly
 * @property string $revenue_b2b_grp_currency_qtd_ly
 * @property string $revenue_b2b_grp_currency_mtd_ly
 * @property string $revenue_b2b_grp_currency_wtd_ly
 * @property string $revenue_b2b_grp_currency_tdy_ly
 * @property string $revenue_b2b_grp_currency_lm_ly
 * @property string $revenue_b2b_grp_currency_lw_ly
 * @property string $revenue_b2b_grp_currency_ld_ly
 * @property string $revenue_b2b_grp_currency_py1
 * @property string $revenue_b2b_grp_currency_py2
 * @property string $revenue_b2b_grp_currency_py3
 * @property string $revenue_b2b_grp_currency_py4
 * @property string $revenue_b2b_grp_currency_py5
 * @property string $revenue_b2b_grp_currency_pq1
 * @property string $revenue_b2b_grp_currency_pq2
 * @property string $revenue_b2b_grp_currency_pq3
 * @property string $revenue_b2b_grp_currency_pq4
 * @property string $revenue_b2b_grp_currency_pq5
 * @property string $profit_b2b_grp_currency_all
 * @property string $profit_b2b_grp_currency_1y
 * @property string $profit_b2b_grp_currency_1q
 * @property string $profit_b2b_grp_currency_1m
 * @property string $profit_b2b_grp_currency_1w
 * @property string $profit_b2b_grp_currency_3d
 * @property string $profit_b2b_grp_currency_ytd
 * @property string $profit_b2b_grp_currency_qtd
 * @property string $profit_b2b_grp_currency_mtd
 * @property string $profit_b2b_grp_currency_wtd
 * @property string $profit_b2b_grp_currency_tdy
 * @property string $profit_b2b_grp_currency_lm
 * @property string $profit_b2b_grp_currency_lw
 * @property string $profit_b2b_grp_currency_ld
 * @property string $profit_b2b_grp_currency_1y_ly
 * @property string $profit_b2b_grp_currency_1q_ly
 * @property string $profit_b2b_grp_currency_1m_ly
 * @property string $profit_b2b_grp_currency_1w_ly
 * @property string $profit_b2b_grp_currency_3d_ly
 * @property string $profit_b2b_grp_currency_ytd_ly
 * @property string $profit_b2b_grp_currency_qtd_ly
 * @property string $profit_b2b_grp_currency_mtd_ly
 * @property string $profit_b2b_grp_currency_wtd_ly
 * @property string $profit_b2b_grp_currency_tdy_ly
 * @property string $profit_b2b_grp_currency_lm_ly
 * @property string $profit_b2b_grp_currency_lw_ly
 * @property string $profit_b2b_grp_currency_ld_ly
 * @property string $profit_b2b_grp_currency_py1
 * @property string $profit_b2b_grp_currency_py2
 * @property string $profit_b2b_grp_currency_py3
 * @property string $profit_b2b_grp_currency_py4
 * @property string $profit_b2b_grp_currency_py5
 * @property string $profit_b2b_grp_currency_pq1
 * @property string $profit_b2b_grp_currency_pq2
 * @property string $profit_b2b_grp_currency_pq3
 * @property string $profit_b2b_grp_currency_pq4
 * @property string $profit_b2b_grp_currency_pq5
 * @property string|null $revenue_b2b_data_all
 * @property string|null $revenue_b2b_data_1y
 * @property string|null $revenue_b2b_data_1q
 * @property string|null $revenue_b2b_data_1m
 * @property string|null $revenue_b2b_data_1w
 * @property string|null $revenue_b2b_data_3d
 * @property string|null $revenue_b2b_data_ytd
 * @property string|null $revenue_b2b_data_qtd
 * @property string|null $revenue_b2b_data_mtd
 * @property string|null $revenue_b2b_data_wtd
 * @property string|null $revenue_b2b_data_tdy
 * @property string|null $revenue_b2b_data_lm
 * @property string|null $revenue_b2b_data_lw
 * @property string|null $revenue_b2b_data_ld
 * @property string|null $revenue_b2b_data_1y_ly
 * @property string|null $revenue_b2b_data_1q_ly
 * @property string|null $revenue_b2b_data_1m_ly
 * @property string|null $revenue_b2b_data_1w_ly
 * @property string|null $revenue_b2b_data_3d_ly
 * @property string|null $revenue_b2b_data_ytd_ly
 * @property string|null $revenue_b2b_data_qtd_ly
 * @property string|null $revenue_b2b_data_mtd_ly
 * @property string|null $revenue_b2b_data_wtd_ly
 * @property string|null $revenue_b2b_data_tdy_ly
 * @property string|null $revenue_b2b_data_lm_ly
 * @property string|null $revenue_b2b_data_lw_ly
 * @property string|null $revenue_b2b_data_ld_ly
 * @property string|null $revenue_b2b_data_py1
 * @property string|null $revenue_b2b_data_py2
 * @property string|null $revenue_b2b_data_py3
 * @property string|null $revenue_b2b_data_py4
 * @property string|null $revenue_b2b_data_py5
 * @property string|null $revenue_b2b_data_pq1
 * @property string|null $revenue_b2b_data_pq2
 * @property string|null $revenue_b2b_data_pq3
 * @property string|null $revenue_b2b_data_pq4
 * @property string|null $revenue_b2b_data_pq5
 * @property int $b2b_number_invoices_all
 * @property int $b2b_number_invoices_1y
 * @property int $b2b_number_invoices_1q
 * @property int $b2b_number_invoices_1m
 * @property int $b2b_number_invoices_1w
 * @property int $b2b_number_invoices_3d
 * @property int $b2b_number_invoices_ytd
 * @property int $b2b_number_invoices_qtd
 * @property int $b2b_number_invoices_mtd
 * @property int $b2b_number_invoices_wtd
 * @property int $b2b_number_invoices_tdy
 * @property int $b2b_number_invoices_lm
 * @property int $b2b_number_invoices_lw
 * @property int $b2b_number_invoices_ld
 * @property int $b2b_number_invoices_1y_ly
 * @property int $b2b_number_invoices_1q_ly
 * @property int $b2b_number_invoices_1m_ly
 * @property int $b2b_number_invoices_1w_ly
 * @property int $b2b_number_invoices_3d_ly
 * @property int $b2b_number_invoices_ytd_ly
 * @property int $b2b_number_invoices_qtd_ly
 * @property int $b2b_number_invoices_mtd_ly
 * @property int $b2b_number_invoices_wtd_ly
 * @property int $b2b_number_invoices_tdy_ly
 * @property int $b2b_number_invoices_lm_ly
 * @property int $b2b_number_invoices_lw_ly
 * @property int $b2b_number_invoices_ld_ly
 * @property int $b2b_number_invoices_py1
 * @property int $b2b_number_invoices_py2
 * @property int $b2b_number_invoices_py3
 * @property int $b2b_number_invoices_py4
 * @property int $b2b_number_invoices_py5
 * @property int $b2b_number_invoices_pq1
 * @property int $b2b_number_invoices_pq2
 * @property int $b2b_number_invoices_pq3
 * @property int $b2b_number_invoices_pq4
 * @property int $b2b_number_invoices_pq5
 * @property int $b2b_number_customers_all
 * @property int $b2b_number_customers_1y
 * @property int $b2b_number_customers_1q
 * @property int $b2b_number_customers_1m
 * @property int $b2b_number_customers_1w
 * @property int $b2b_number_customers_3d
 * @property int $b2b_number_customers_ytd
 * @property int $b2b_number_customers_qtd
 * @property int $b2b_number_customers_mtd
 * @property int $b2b_number_customers_wtd
 * @property int $b2b_number_customers_tdy
 * @property int $b2b_number_customers_lm
 * @property int $b2b_number_customers_lw
 * @property int $b2b_number_customers_ld
 * @property int $b2b_number_customers_1y_ly
 * @property int $b2b_number_customers_1q_ly
 * @property int $b2b_number_customers_1m_ly
 * @property int $b2b_number_customers_1w_ly
 * @property int $b2b_number_customers_3d_ly
 * @property int $b2b_number_customers_ytd_ly
 * @property int $b2b_number_customers_qtd_ly
 * @property int $b2b_number_customers_mtd_ly
 * @property int $b2b_number_customers_wtd_ly
 * @property int $b2b_number_customers_tdy_ly
 * @property int $b2b_number_customers_lm_ly
 * @property int $b2b_number_customers_lw_ly
 * @property int $b2b_number_customers_ld_ly
 * @property int $b2b_number_customers_py1
 * @property int $b2b_number_customers_py2
 * @property int $b2b_number_customers_py3
 * @property int $b2b_number_customers_py4
 * @property int $b2b_number_customers_py5
 * @property int $b2b_number_customers_pq1
 * @property int $b2b_number_customers_pq2
 * @property int $b2b_number_customers_pq3
 * @property int $b2b_number_customers_pq4
 * @property int $b2b_number_customers_pq5
 * @property string $revenue_dropshipping_grp_currency_all
 * @property string $revenue_dropshipping_grp_currency_1y
 * @property string $revenue_dropshipping_grp_currency_1q
 * @property string $revenue_dropshipping_grp_currency_1m
 * @property string $revenue_dropshipping_grp_currency_1w
 * @property string $revenue_dropshipping_grp_currency_3d
 * @property string $revenue_dropshipping_grp_currency_ytd
 * @property string $revenue_dropshipping_grp_currency_qtd
 * @property string $revenue_dropshipping_grp_currency_mtd
 * @property string $revenue_dropshipping_grp_currency_wtd
 * @property string $revenue_dropshipping_grp_currency_tdy
 * @property string $revenue_dropshipping_grp_currency_lm
 * @property string $revenue_dropshipping_grp_currency_lw
 * @property string $revenue_dropshipping_grp_currency_ld
 * @property string $revenue_dropshipping_grp_currency_1y_ly
 * @property string $revenue_dropshipping_grp_currency_1q_ly
 * @property string $revenue_dropshipping_grp_currency_1m_ly
 * @property string $revenue_dropshipping_grp_currency_1w_ly
 * @property string $revenue_dropshipping_grp_currency_3d_ly
 * @property string $revenue_dropshipping_grp_currency_ytd_ly
 * @property string $revenue_dropshipping_grp_currency_qtd_ly
 * @property string $revenue_dropshipping_grp_currency_mtd_ly
 * @property string $revenue_dropshipping_grp_currency_wtd_ly
 * @property string $revenue_dropshipping_grp_currency_tdy_ly
 * @property string $revenue_dropshipping_grp_currency_lm_ly
 * @property string $revenue_dropshipping_grp_currency_lw_ly
 * @property string $revenue_dropshipping_grp_currency_ld_ly
 * @property string $revenue_dropshipping_grp_currency_py1
 * @property string $revenue_dropshipping_grp_currency_py2
 * @property string $revenue_dropshipping_grp_currency_py3
 * @property string $revenue_dropshipping_grp_currency_py4
 * @property string $revenue_dropshipping_grp_currency_py5
 * @property string $revenue_dropshipping_grp_currency_pq1
 * @property string $revenue_dropshipping_grp_currency_pq2
 * @property string $revenue_dropshipping_grp_currency_pq3
 * @property string $revenue_dropshipping_grp_currency_pq4
 * @property string $revenue_dropshipping_grp_currency_pq5
 * @property string $profit_dropshipping_grp_currency_all
 * @property string $profit_dropshipping_grp_currency_1y
 * @property string $profit_dropshipping_grp_currency_1q
 * @property string $profit_dropshipping_grp_currency_1m
 * @property string $profit_dropshipping_grp_currency_1w
 * @property string $profit_dropshipping_grp_currency_3d
 * @property string $profit_dropshipping_grp_currency_ytd
 * @property string $profit_dropshipping_grp_currency_qtd
 * @property string $profit_dropshipping_grp_currency_mtd
 * @property string $profit_dropshipping_grp_currency_wtd
 * @property string $profit_dropshipping_grp_currency_tdy
 * @property string $profit_dropshipping_grp_currency_lm
 * @property string $profit_dropshipping_grp_currency_lw
 * @property string $profit_dropshipping_grp_currency_ld
 * @property string $profit_dropshipping_grp_currency_1y_ly
 * @property string $profit_dropshipping_grp_currency_1q_ly
 * @property string $profit_dropshipping_grp_currency_1m_ly
 * @property string $profit_dropshipping_grp_currency_1w_ly
 * @property string $profit_dropshipping_grp_currency_3d_ly
 * @property string $profit_dropshipping_grp_currency_ytd_ly
 * @property string $profit_dropshipping_grp_currency_qtd_ly
 * @property string $profit_dropshipping_grp_currency_mtd_ly
 * @property string $profit_dropshipping_grp_currency_wtd_ly
 * @property string $profit_dropshipping_grp_currency_tdy_ly
 * @property string $profit_dropshipping_grp_currency_lm_ly
 * @property string $profit_dropshipping_grp_currency_lw_ly
 * @property string $profit_dropshipping_grp_currency_ld_ly
 * @property string $profit_dropshipping_grp_currency_py1
 * @property string $profit_dropshipping_grp_currency_py2
 * @property string $profit_dropshipping_grp_currency_py3
 * @property string $profit_dropshipping_grp_currency_py4
 * @property string $profit_dropshipping_grp_currency_py5
 * @property string $profit_dropshipping_grp_currency_pq1
 * @property string $profit_dropshipping_grp_currency_pq2
 * @property string $profit_dropshipping_grp_currency_pq3
 * @property string $profit_dropshipping_grp_currency_pq4
 * @property string $profit_dropshipping_grp_currency_pq5
 * @property string|null $revenue_dropshipping_data_all
 * @property string|null $revenue_dropshipping_data_1y
 * @property string|null $revenue_dropshipping_data_1q
 * @property string|null $revenue_dropshipping_data_1m
 * @property string|null $revenue_dropshipping_data_1w
 * @property string|null $revenue_dropshipping_data_3d
 * @property string|null $revenue_dropshipping_data_ytd
 * @property string|null $revenue_dropshipping_data_qtd
 * @property string|null $revenue_dropshipping_data_mtd
 * @property string|null $revenue_dropshipping_data_wtd
 * @property string|null $revenue_dropshipping_data_tdy
 * @property string|null $revenue_dropshipping_data_lm
 * @property string|null $revenue_dropshipping_data_lw
 * @property string|null $revenue_dropshipping_data_ld
 * @property string|null $revenue_dropshipping_data_1y_ly
 * @property string|null $revenue_dropshipping_data_1q_ly
 * @property string|null $revenue_dropshipping_data_1m_ly
 * @property string|null $revenue_dropshipping_data_1w_ly
 * @property string|null $revenue_dropshipping_data_3d_ly
 * @property string|null $revenue_dropshipping_data_ytd_ly
 * @property string|null $revenue_dropshipping_data_qtd_ly
 * @property string|null $revenue_dropshipping_data_mtd_ly
 * @property string|null $revenue_dropshipping_data_wtd_ly
 * @property string|null $revenue_dropshipping_data_tdy_ly
 * @property string|null $revenue_dropshipping_data_lm_ly
 * @property string|null $revenue_dropshipping_data_lw_ly
 * @property string|null $revenue_dropshipping_data_ld_ly
 * @property string|null $revenue_dropshipping_data_py1
 * @property string|null $revenue_dropshipping_data_py2
 * @property string|null $revenue_dropshipping_data_py3
 * @property string|null $revenue_dropshipping_data_py4
 * @property string|null $revenue_dropshipping_data_py5
 * @property string|null $revenue_dropshipping_data_pq1
 * @property string|null $revenue_dropshipping_data_pq2
 * @property string|null $revenue_dropshipping_data_pq3
 * @property string|null $revenue_dropshipping_data_pq4
 * @property string|null $revenue_dropshipping_data_pq5
 * @property int $dropshipping_number_invoices_all
 * @property int $dropshipping_number_invoices_1y
 * @property int $dropshipping_number_invoices_1q
 * @property int $dropshipping_number_invoices_1m
 * @property int $dropshipping_number_invoices_1w
 * @property int $dropshipping_number_invoices_3d
 * @property int $dropshipping_number_invoices_ytd
 * @property int $dropshipping_number_invoices_qtd
 * @property int $dropshipping_number_invoices_mtd
 * @property int $dropshipping_number_invoices_wtd
 * @property int $dropshipping_number_invoices_tdy
 * @property int $dropshipping_number_invoices_lm
 * @property int $dropshipping_number_invoices_lw
 * @property int $dropshipping_number_invoices_ld
 * @property int $dropshipping_number_invoices_1y_ly
 * @property int $dropshipping_number_invoices_1q_ly
 * @property int $dropshipping_number_invoices_1m_ly
 * @property int $dropshipping_number_invoices_1w_ly
 * @property int $dropshipping_number_invoices_3d_ly
 * @property int $dropshipping_number_invoices_ytd_ly
 * @property int $dropshipping_number_invoices_qtd_ly
 * @property int $dropshipping_number_invoices_mtd_ly
 * @property int $dropshipping_number_invoices_wtd_ly
 * @property int $dropshipping_number_invoices_tdy_ly
 * @property int $dropshipping_number_invoices_lm_ly
 * @property int $dropshipping_number_invoices_lw_ly
 * @property int $dropshipping_number_invoices_ld_ly
 * @property int $dropshipping_number_invoices_py1
 * @property int $dropshipping_number_invoices_py2
 * @property int $dropshipping_number_invoices_py3
 * @property int $dropshipping_number_invoices_py4
 * @property int $dropshipping_number_invoices_py5
 * @property int $dropshipping_number_invoices_pq1
 * @property int $dropshipping_number_invoices_pq2
 * @property int $dropshipping_number_invoices_pq3
 * @property int $dropshipping_number_invoices_pq4
 * @property int $dropshipping_number_invoices_pq5
 * @property int $dropshipping_number_customers_all
 * @property int $dropshipping_number_customers_1y
 * @property int $dropshipping_number_customers_1q
 * @property int $dropshipping_number_customers_1m
 * @property int $dropshipping_number_customers_1w
 * @property int $dropshipping_number_customers_3d
 * @property int $dropshipping_number_customers_ytd
 * @property int $dropshipping_number_customers_qtd
 * @property int $dropshipping_number_customers_mtd
 * @property int $dropshipping_number_customers_wtd
 * @property int $dropshipping_number_customers_tdy
 * @property int $dropshipping_number_customers_lm
 * @property int $dropshipping_number_customers_lw
 * @property int $dropshipping_number_customers_ld
 * @property int $dropshipping_number_customers_1y_ly
 * @property int $dropshipping_number_customers_1q_ly
 * @property int $dropshipping_number_customers_1m_ly
 * @property int $dropshipping_number_customers_1w_ly
 * @property int $dropshipping_number_customers_3d_ly
 * @property int $dropshipping_number_customers_ytd_ly
 * @property int $dropshipping_number_customers_qtd_ly
 * @property int $dropshipping_number_customers_mtd_ly
 * @property int $dropshipping_number_customers_wtd_ly
 * @property int $dropshipping_number_customers_tdy_ly
 * @property int $dropshipping_number_customers_lm_ly
 * @property int $dropshipping_number_customers_lw_ly
 * @property int $dropshipping_number_customers_ld_ly
 * @property int $dropshipping_number_customers_py1
 * @property int $dropshipping_number_customers_py2
 * @property int $dropshipping_number_customers_py3
 * @property int $dropshipping_number_customers_py4
 * @property int $dropshipping_number_customers_py5
 * @property int $dropshipping_number_customers_pq1
 * @property int $dropshipping_number_customers_pq2
 * @property int $dropshipping_number_customers_pq3
 * @property int $dropshipping_number_customers_pq4
 * @property int $dropshipping_number_customers_pq5
 * @property string $revenue_marketplace_grp_currency_all
 * @property string $revenue_marketplace_grp_currency_1y
 * @property string $revenue_marketplace_grp_currency_1q
 * @property string $revenue_marketplace_grp_currency_1m
 * @property string $revenue_marketplace_grp_currency_1w
 * @property string $revenue_marketplace_grp_currency_3d
 * @property string $revenue_marketplace_grp_currency_ytd
 * @property string $revenue_marketplace_grp_currency_qtd
 * @property string $revenue_marketplace_grp_currency_mtd
 * @property string $revenue_marketplace_grp_currency_wtd
 * @property string $revenue_marketplace_grp_currency_tdy
 * @property string $revenue_marketplace_grp_currency_lm
 * @property string $revenue_marketplace_grp_currency_lw
 * @property string $revenue_marketplace_grp_currency_ld
 * @property string $revenue_marketplace_grp_currency_1y_ly
 * @property string $revenue_marketplace_grp_currency_1q_ly
 * @property string $revenue_marketplace_grp_currency_1m_ly
 * @property string $revenue_marketplace_grp_currency_1w_ly
 * @property string $revenue_marketplace_grp_currency_3d_ly
 * @property string $revenue_marketplace_grp_currency_ytd_ly
 * @property string $revenue_marketplace_grp_currency_qtd_ly
 * @property string $revenue_marketplace_grp_currency_mtd_ly
 * @property string $revenue_marketplace_grp_currency_wtd_ly
 * @property string $revenue_marketplace_grp_currency_tdy_ly
 * @property string $revenue_marketplace_grp_currency_lm_ly
 * @property string $revenue_marketplace_grp_currency_lw_ly
 * @property string $revenue_marketplace_grp_currency_ld_ly
 * @property string $revenue_marketplace_grp_currency_py1
 * @property string $revenue_marketplace_grp_currency_py2
 * @property string $revenue_marketplace_grp_currency_py3
 * @property string $revenue_marketplace_grp_currency_py4
 * @property string $revenue_marketplace_grp_currency_py5
 * @property string $revenue_marketplace_grp_currency_pq1
 * @property string $revenue_marketplace_grp_currency_pq2
 * @property string $revenue_marketplace_grp_currency_pq3
 * @property string $revenue_marketplace_grp_currency_pq4
 * @property string $revenue_marketplace_grp_currency_pq5
 * @property string $profit_marketplace_grp_currency_all
 * @property string $profit_marketplace_grp_currency_1y
 * @property string $profit_marketplace_grp_currency_1q
 * @property string $profit_marketplace_grp_currency_1m
 * @property string $profit_marketplace_grp_currency_1w
 * @property string $profit_marketplace_grp_currency_3d
 * @property string $profit_marketplace_grp_currency_ytd
 * @property string $profit_marketplace_grp_currency_qtd
 * @property string $profit_marketplace_grp_currency_mtd
 * @property string $profit_marketplace_grp_currency_wtd
 * @property string $profit_marketplace_grp_currency_tdy
 * @property string $profit_marketplace_grp_currency_lm
 * @property string $profit_marketplace_grp_currency_lw
 * @property string $profit_marketplace_grp_currency_ld
 * @property string $profit_marketplace_grp_currency_1y_ly
 * @property string $profit_marketplace_grp_currency_1q_ly
 * @property string $profit_marketplace_grp_currency_1m_ly
 * @property string $profit_marketplace_grp_currency_1w_ly
 * @property string $profit_marketplace_grp_currency_3d_ly
 * @property string $profit_marketplace_grp_currency_ytd_ly
 * @property string $profit_marketplace_grp_currency_qtd_ly
 * @property string $profit_marketplace_grp_currency_mtd_ly
 * @property string $profit_marketplace_grp_currency_wtd_ly
 * @property string $profit_marketplace_grp_currency_tdy_ly
 * @property string $profit_marketplace_grp_currency_lm_ly
 * @property string $profit_marketplace_grp_currency_lw_ly
 * @property string $profit_marketplace_grp_currency_ld_ly
 * @property string $profit_marketplace_grp_currency_py1
 * @property string $profit_marketplace_grp_currency_py2
 * @property string $profit_marketplace_grp_currency_py3
 * @property string $profit_marketplace_grp_currency_py4
 * @property string $profit_marketplace_grp_currency_py5
 * @property string $profit_marketplace_grp_currency_pq1
 * @property string $profit_marketplace_grp_currency_pq2
 * @property string $profit_marketplace_grp_currency_pq3
 * @property string $profit_marketplace_grp_currency_pq4
 * @property string $profit_marketplace_grp_currency_pq5
 * @property string|null $revenue_marketplace_data_all
 * @property string|null $revenue_marketplace_data_1y
 * @property string|null $revenue_marketplace_data_1q
 * @property string|null $revenue_marketplace_data_1m
 * @property string|null $revenue_marketplace_data_1w
 * @property string|null $revenue_marketplace_data_3d
 * @property string|null $revenue_marketplace_data_ytd
 * @property string|null $revenue_marketplace_data_qtd
 * @property string|null $revenue_marketplace_data_mtd
 * @property string|null $revenue_marketplace_data_wtd
 * @property string|null $revenue_marketplace_data_tdy
 * @property string|null $revenue_marketplace_data_lm
 * @property string|null $revenue_marketplace_data_lw
 * @property string|null $revenue_marketplace_data_ld
 * @property string|null $revenue_marketplace_data_1y_ly
 * @property string|null $revenue_marketplace_data_1q_ly
 * @property string|null $revenue_marketplace_data_1m_ly
 * @property string|null $revenue_marketplace_data_1w_ly
 * @property string|null $revenue_marketplace_data_3d_ly
 * @property string|null $revenue_marketplace_data_ytd_ly
 * @property string|null $revenue_marketplace_data_qtd_ly
 * @property string|null $revenue_marketplace_data_mtd_ly
 * @property string|null $revenue_marketplace_data_wtd_ly
 * @property string|null $revenue_marketplace_data_tdy_ly
 * @property string|null $revenue_marketplace_data_lm_ly
 * @property string|null $revenue_marketplace_data_lw_ly
 * @property string|null $revenue_marketplace_data_ld_ly
 * @property string|null $revenue_marketplace_data_py1
 * @property string|null $revenue_marketplace_data_py2
 * @property string|null $revenue_marketplace_data_py3
 * @property string|null $revenue_marketplace_data_py4
 * @property string|null $revenue_marketplace_data_py5
 * @property string|null $revenue_marketplace_data_pq1
 * @property string|null $revenue_marketplace_data_pq2
 * @property string|null $revenue_marketplace_data_pq3
 * @property string|null $revenue_marketplace_data_pq4
 * @property string|null $revenue_marketplace_data_pq5
 * @property int $marketplace_number_invoices_all
 * @property int $marketplace_number_invoices_1y
 * @property int $marketplace_number_invoices_1q
 * @property int $marketplace_number_invoices_1m
 * @property int $marketplace_number_invoices_1w
 * @property int $marketplace_number_invoices_3d
 * @property int $marketplace_number_invoices_ytd
 * @property int $marketplace_number_invoices_qtd
 * @property int $marketplace_number_invoices_mtd
 * @property int $marketplace_number_invoices_wtd
 * @property int $marketplace_number_invoices_tdy
 * @property int $marketplace_number_invoices_lm
 * @property int $marketplace_number_invoices_lw
 * @property int $marketplace_number_invoices_ld
 * @property int $marketplace_number_invoices_1y_ly
 * @property int $marketplace_number_invoices_1q_ly
 * @property int $marketplace_number_invoices_1m_ly
 * @property int $marketplace_number_invoices_1w_ly
 * @property int $marketplace_number_invoices_3d_ly
 * @property int $marketplace_number_invoices_ytd_ly
 * @property int $marketplace_number_invoices_qtd_ly
 * @property int $marketplace_number_invoices_mtd_ly
 * @property int $marketplace_number_invoices_wtd_ly
 * @property int $marketplace_number_invoices_tdy_ly
 * @property int $marketplace_number_invoices_lm_ly
 * @property int $marketplace_number_invoices_lw_ly
 * @property int $marketplace_number_invoices_ld_ly
 * @property int $marketplace_number_invoices_py1
 * @property int $marketplace_number_invoices_py2
 * @property int $marketplace_number_invoices_py3
 * @property int $marketplace_number_invoices_py4
 * @property int $marketplace_number_invoices_py5
 * @property int $marketplace_number_invoices_pq1
 * @property int $marketplace_number_invoices_pq2
 * @property int $marketplace_number_invoices_pq3
 * @property int $marketplace_number_invoices_pq4
 * @property int $marketplace_number_invoices_pq5
 * @property int $marketplace_number_customers_all
 * @property int $marketplace_number_customers_1y
 * @property int $marketplace_number_customers_1q
 * @property int $marketplace_number_customers_1m
 * @property int $marketplace_number_customers_1w
 * @property int $marketplace_number_customers_3d
 * @property int $marketplace_number_customers_ytd
 * @property int $marketplace_number_customers_qtd
 * @property int $marketplace_number_customers_mtd
 * @property int $marketplace_number_customers_wtd
 * @property int $marketplace_number_customers_tdy
 * @property int $marketplace_number_customers_lm
 * @property int $marketplace_number_customers_lw
 * @property int $marketplace_number_customers_ld
 * @property int $marketplace_number_customers_1y_ly
 * @property int $marketplace_number_customers_1q_ly
 * @property int $marketplace_number_customers_1m_ly
 * @property int $marketplace_number_customers_1w_ly
 * @property int $marketplace_number_customers_3d_ly
 * @property int $marketplace_number_customers_ytd_ly
 * @property int $marketplace_number_customers_qtd_ly
 * @property int $marketplace_number_customers_mtd_ly
 * @property int $marketplace_number_customers_wtd_ly
 * @property int $marketplace_number_customers_tdy_ly
 * @property int $marketplace_number_customers_lm_ly
 * @property int $marketplace_number_customers_lw_ly
 * @property int $marketplace_number_customers_ld_ly
 * @property int $marketplace_number_customers_py1
 * @property int $marketplace_number_customers_py2
 * @property int $marketplace_number_customers_py3
 * @property int $marketplace_number_customers_py4
 * @property int $marketplace_number_customers_py5
 * @property int $marketplace_number_customers_pq1
 * @property int $marketplace_number_customers_pq2
 * @property int $marketplace_number_customers_pq3
 * @property int $marketplace_number_customers_pq4
 * @property int $marketplace_number_customers_pq5
 * @property string $revenue_partner_grp_currency_all
 * @property string $revenue_partner_grp_currency_1y
 * @property string $revenue_partner_grp_currency_1q
 * @property string $revenue_partner_grp_currency_1m
 * @property string $revenue_partner_grp_currency_1w
 * @property string $revenue_partner_grp_currency_3d
 * @property string $revenue_partner_grp_currency_ytd
 * @property string $revenue_partner_grp_currency_qtd
 * @property string $revenue_partner_grp_currency_mtd
 * @property string $revenue_partner_grp_currency_wtd
 * @property string $revenue_partner_grp_currency_tdy
 * @property string $revenue_partner_grp_currency_lm
 * @property string $revenue_partner_grp_currency_lw
 * @property string $revenue_partner_grp_currency_ld
 * @property string $revenue_partner_grp_currency_1y_ly
 * @property string $revenue_partner_grp_currency_1q_ly
 * @property string $revenue_partner_grp_currency_1m_ly
 * @property string $revenue_partner_grp_currency_1w_ly
 * @property string $revenue_partner_grp_currency_3d_ly
 * @property string $revenue_partner_grp_currency_ytd_ly
 * @property string $revenue_partner_grp_currency_qtd_ly
 * @property string $revenue_partner_grp_currency_mtd_ly
 * @property string $revenue_partner_grp_currency_wtd_ly
 * @property string $revenue_partner_grp_currency_tdy_ly
 * @property string $revenue_partner_grp_currency_lm_ly
 * @property string $revenue_partner_grp_currency_lw_ly
 * @property string $revenue_partner_grp_currency_ld_ly
 * @property string $revenue_partner_grp_currency_py1
 * @property string $revenue_partner_grp_currency_py2
 * @property string $revenue_partner_grp_currency_py3
 * @property string $revenue_partner_grp_currency_py4
 * @property string $revenue_partner_grp_currency_py5
 * @property string $revenue_partner_grp_currency_pq1
 * @property string $revenue_partner_grp_currency_pq2
 * @property string $revenue_partner_grp_currency_pq3
 * @property string $revenue_partner_grp_currency_pq4
 * @property string $revenue_partner_grp_currency_pq5
 * @property string $profit_partner_grp_currency_all
 * @property string $profit_partner_grp_currency_1y
 * @property string $profit_partner_grp_currency_1q
 * @property string $profit_partner_grp_currency_1m
 * @property string $profit_partner_grp_currency_1w
 * @property string $profit_partner_grp_currency_3d
 * @property string $profit_partner_grp_currency_ytd
 * @property string $profit_partner_grp_currency_qtd
 * @property string $profit_partner_grp_currency_mtd
 * @property string $profit_partner_grp_currency_wtd
 * @property string $profit_partner_grp_currency_tdy
 * @property string $profit_partner_grp_currency_lm
 * @property string $profit_partner_grp_currency_lw
 * @property string $profit_partner_grp_currency_ld
 * @property string $profit_partner_grp_currency_1y_ly
 * @property string $profit_partner_grp_currency_1q_ly
 * @property string $profit_partner_grp_currency_1m_ly
 * @property string $profit_partner_grp_currency_1w_ly
 * @property string $profit_partner_grp_currency_3d_ly
 * @property string $profit_partner_grp_currency_ytd_ly
 * @property string $profit_partner_grp_currency_qtd_ly
 * @property string $profit_partner_grp_currency_mtd_ly
 * @property string $profit_partner_grp_currency_wtd_ly
 * @property string $profit_partner_grp_currency_tdy_ly
 * @property string $profit_partner_grp_currency_lm_ly
 * @property string $profit_partner_grp_currency_lw_ly
 * @property string $profit_partner_grp_currency_ld_ly
 * @property string $profit_partner_grp_currency_py1
 * @property string $profit_partner_grp_currency_py2
 * @property string $profit_partner_grp_currency_py3
 * @property string $profit_partner_grp_currency_py4
 * @property string $profit_partner_grp_currency_py5
 * @property string $profit_partner_grp_currency_pq1
 * @property string $profit_partner_grp_currency_pq2
 * @property string $profit_partner_grp_currency_pq3
 * @property string $profit_partner_grp_currency_pq4
 * @property string $profit_partner_grp_currency_pq5
 * @property string|null $revenue_partner_data_all
 * @property string|null $revenue_partner_data_1y
 * @property string|null $revenue_partner_data_1q
 * @property string|null $revenue_partner_data_1m
 * @property string|null $revenue_partner_data_1w
 * @property string|null $revenue_partner_data_3d
 * @property string|null $revenue_partner_data_ytd
 * @property string|null $revenue_partner_data_qtd
 * @property string|null $revenue_partner_data_mtd
 * @property string|null $revenue_partner_data_wtd
 * @property string|null $revenue_partner_data_tdy
 * @property string|null $revenue_partner_data_lm
 * @property string|null $revenue_partner_data_lw
 * @property string|null $revenue_partner_data_ld
 * @property string|null $revenue_partner_data_1y_ly
 * @property string|null $revenue_partner_data_1q_ly
 * @property string|null $revenue_partner_data_1m_ly
 * @property string|null $revenue_partner_data_1w_ly
 * @property string|null $revenue_partner_data_3d_ly
 * @property string|null $revenue_partner_data_ytd_ly
 * @property string|null $revenue_partner_data_qtd_ly
 * @property string|null $revenue_partner_data_mtd_ly
 * @property string|null $revenue_partner_data_wtd_ly
 * @property string|null $revenue_partner_data_tdy_ly
 * @property string|null $revenue_partner_data_lm_ly
 * @property string|null $revenue_partner_data_lw_ly
 * @property string|null $revenue_partner_data_ld_ly
 * @property string|null $revenue_partner_data_py1
 * @property string|null $revenue_partner_data_py2
 * @property string|null $revenue_partner_data_py3
 * @property string|null $revenue_partner_data_py4
 * @property string|null $revenue_partner_data_py5
 * @property string|null $revenue_partner_data_pq1
 * @property string|null $revenue_partner_data_pq2
 * @property string|null $revenue_partner_data_pq3
 * @property string|null $revenue_partner_data_pq4
 * @property string|null $revenue_partner_data_pq5
 * @property int $partner_number_invoices_all
 * @property int $partner_number_invoices_1y
 * @property int $partner_number_invoices_1q
 * @property int $partner_number_invoices_1m
 * @property int $partner_number_invoices_1w
 * @property int $partner_number_invoices_3d
 * @property int $partner_number_invoices_ytd
 * @property int $partner_number_invoices_qtd
 * @property int $partner_number_invoices_mtd
 * @property int $partner_number_invoices_wtd
 * @property int $partner_number_invoices_tdy
 * @property int $partner_number_invoices_lm
 * @property int $partner_number_invoices_lw
 * @property int $partner_number_invoices_ld
 * @property int $partner_number_invoices_1y_ly
 * @property int $partner_number_invoices_1q_ly
 * @property int $partner_number_invoices_1m_ly
 * @property int $partner_number_invoices_1w_ly
 * @property int $partner_number_invoices_3d_ly
 * @property int $partner_number_invoices_ytd_ly
 * @property int $partner_number_invoices_qtd_ly
 * @property int $partner_number_invoices_mtd_ly
 * @property int $partner_number_invoices_wtd_ly
 * @property int $partner_number_invoices_tdy_ly
 * @property int $partner_number_invoices_lm_ly
 * @property int $partner_number_invoices_lw_ly
 * @property int $partner_number_invoices_ld_ly
 * @property int $partner_number_invoices_py1
 * @property int $partner_number_invoices_py2
 * @property int $partner_number_invoices_py3
 * @property int $partner_number_invoices_py4
 * @property int $partner_number_invoices_py5
 * @property int $partner_number_invoices_pq1
 * @property int $partner_number_invoices_pq2
 * @property int $partner_number_invoices_pq3
 * @property int $partner_number_invoices_pq4
 * @property int $partner_number_invoices_pq5
 * @property int $partner_number_customers_all
 * @property int $partner_number_customers_1y
 * @property int $partner_number_customers_1q
 * @property int $partner_number_customers_1m
 * @property int $partner_number_customers_1w
 * @property int $partner_number_customers_3d
 * @property int $partner_number_customers_ytd
 * @property int $partner_number_customers_qtd
 * @property int $partner_number_customers_mtd
 * @property int $partner_number_customers_wtd
 * @property int $partner_number_customers_tdy
 * @property int $partner_number_customers_lm
 * @property int $partner_number_customers_lw
 * @property int $partner_number_customers_ld
 * @property int $partner_number_customers_1y_ly
 * @property int $partner_number_customers_1q_ly
 * @property int $partner_number_customers_1m_ly
 * @property int $partner_number_customers_1w_ly
 * @property int $partner_number_customers_3d_ly
 * @property int $partner_number_customers_ytd_ly
 * @property int $partner_number_customers_qtd_ly
 * @property int $partner_number_customers_mtd_ly
 * @property int $partner_number_customers_wtd_ly
 * @property int $partner_number_customers_tdy_ly
 * @property int $partner_number_customers_lm_ly
 * @property int $partner_number_customers_lw_ly
 * @property int $partner_number_customers_ld_ly
 * @property int $partner_number_customers_py1
 * @property int $partner_number_customers_py2
 * @property int $partner_number_customers_py3
 * @property int $partner_number_customers_py4
 * @property int $partner_number_customers_py5
 * @property int $partner_number_customers_pq1
 * @property int $partner_number_customers_pq2
 * @property int $partner_number_customers_pq3
 * @property int $partner_number_customers_pq4
 * @property int $partner_number_customers_pq5
 * @property string $revenue_employee_grp_currency_all
 * @property string $revenue_employee_grp_currency_1y
 * @property string $revenue_employee_grp_currency_1q
 * @property string $revenue_employee_grp_currency_1m
 * @property string $revenue_employee_grp_currency_1w
 * @property string $revenue_employee_grp_currency_3d
 * @property string $revenue_employee_grp_currency_ytd
 * @property string $revenue_employee_grp_currency_qtd
 * @property string $revenue_employee_grp_currency_mtd
 * @property string $revenue_employee_grp_currency_wtd
 * @property string $revenue_employee_grp_currency_tdy
 * @property string $revenue_employee_grp_currency_lm
 * @property string $revenue_employee_grp_currency_lw
 * @property string $revenue_employee_grp_currency_ld
 * @property string $revenue_employee_grp_currency_1y_ly
 * @property string $revenue_employee_grp_currency_1q_ly
 * @property string $revenue_employee_grp_currency_1m_ly
 * @property string $revenue_employee_grp_currency_1w_ly
 * @property string $revenue_employee_grp_currency_3d_ly
 * @property string $revenue_employee_grp_currency_ytd_ly
 * @property string $revenue_employee_grp_currency_qtd_ly
 * @property string $revenue_employee_grp_currency_mtd_ly
 * @property string $revenue_employee_grp_currency_wtd_ly
 * @property string $revenue_employee_grp_currency_tdy_ly
 * @property string $revenue_employee_grp_currency_lm_ly
 * @property string $revenue_employee_grp_currency_lw_ly
 * @property string $revenue_employee_grp_currency_ld_ly
 * @property string $revenue_employee_grp_currency_py1
 * @property string $revenue_employee_grp_currency_py2
 * @property string $revenue_employee_grp_currency_py3
 * @property string $revenue_employee_grp_currency_py4
 * @property string $revenue_employee_grp_currency_py5
 * @property string $revenue_employee_grp_currency_pq1
 * @property string $revenue_employee_grp_currency_pq2
 * @property string $revenue_employee_grp_currency_pq3
 * @property string $revenue_employee_grp_currency_pq4
 * @property string $revenue_employee_grp_currency_pq5
 * @property string $profit_employee_grp_currency_all
 * @property string $profit_employee_grp_currency_1y
 * @property string $profit_employee_grp_currency_1q
 * @property string $profit_employee_grp_currency_1m
 * @property string $profit_employee_grp_currency_1w
 * @property string $profit_employee_grp_currency_3d
 * @property string $profit_employee_grp_currency_ytd
 * @property string $profit_employee_grp_currency_qtd
 * @property string $profit_employee_grp_currency_mtd
 * @property string $profit_employee_grp_currency_wtd
 * @property string $profit_employee_grp_currency_tdy
 * @property string $profit_employee_grp_currency_lm
 * @property string $profit_employee_grp_currency_lw
 * @property string $profit_employee_grp_currency_ld
 * @property string $profit_employee_grp_currency_1y_ly
 * @property string $profit_employee_grp_currency_1q_ly
 * @property string $profit_employee_grp_currency_1m_ly
 * @property string $profit_employee_grp_currency_1w_ly
 * @property string $profit_employee_grp_currency_3d_ly
 * @property string $profit_employee_grp_currency_ytd_ly
 * @property string $profit_employee_grp_currency_qtd_ly
 * @property string $profit_employee_grp_currency_mtd_ly
 * @property string $profit_employee_grp_currency_wtd_ly
 * @property string $profit_employee_grp_currency_tdy_ly
 * @property string $profit_employee_grp_currency_lm_ly
 * @property string $profit_employee_grp_currency_lw_ly
 * @property string $profit_employee_grp_currency_ld_ly
 * @property string $profit_employee_grp_currency_py1
 * @property string $profit_employee_grp_currency_py2
 * @property string $profit_employee_grp_currency_py3
 * @property string $profit_employee_grp_currency_py4
 * @property string $profit_employee_grp_currency_py5
 * @property string $profit_employee_grp_currency_pq1
 * @property string $profit_employee_grp_currency_pq2
 * @property string $profit_employee_grp_currency_pq3
 * @property string $profit_employee_grp_currency_pq4
 * @property string $profit_employee_grp_currency_pq5
 * @property string|null $revenue_employee_data_all
 * @property string|null $revenue_employee_data_1y
 * @property string|null $revenue_employee_data_1q
 * @property string|null $revenue_employee_data_1m
 * @property string|null $revenue_employee_data_1w
 * @property string|null $revenue_employee_data_3d
 * @property string|null $revenue_employee_data_ytd
 * @property string|null $revenue_employee_data_qtd
 * @property string|null $revenue_employee_data_mtd
 * @property string|null $revenue_employee_data_wtd
 * @property string|null $revenue_employee_data_tdy
 * @property string|null $revenue_employee_data_lm
 * @property string|null $revenue_employee_data_lw
 * @property string|null $revenue_employee_data_ld
 * @property string|null $revenue_employee_data_1y_ly
 * @property string|null $revenue_employee_data_1q_ly
 * @property string|null $revenue_employee_data_1m_ly
 * @property string|null $revenue_employee_data_1w_ly
 * @property string|null $revenue_employee_data_3d_ly
 * @property string|null $revenue_employee_data_ytd_ly
 * @property string|null $revenue_employee_data_qtd_ly
 * @property string|null $revenue_employee_data_mtd_ly
 * @property string|null $revenue_employee_data_wtd_ly
 * @property string|null $revenue_employee_data_tdy_ly
 * @property string|null $revenue_employee_data_lm_ly
 * @property string|null $revenue_employee_data_lw_ly
 * @property string|null $revenue_employee_data_ld_ly
 * @property string|null $revenue_employee_data_py1
 * @property string|null $revenue_employee_data_py2
 * @property string|null $revenue_employee_data_py3
 * @property string|null $revenue_employee_data_py4
 * @property string|null $revenue_employee_data_py5
 * @property string|null $revenue_employee_data_pq1
 * @property string|null $revenue_employee_data_pq2
 * @property string|null $revenue_employee_data_pq3
 * @property string|null $revenue_employee_data_pq4
 * @property string|null $revenue_employee_data_pq5
 * @property int $employee_number_invoices_all
 * @property int $employee_number_invoices_1y
 * @property int $employee_number_invoices_1q
 * @property int $employee_number_invoices_1m
 * @property int $employee_number_invoices_1w
 * @property int $employee_number_invoices_3d
 * @property int $employee_number_invoices_ytd
 * @property int $employee_number_invoices_qtd
 * @property int $employee_number_invoices_mtd
 * @property int $employee_number_invoices_wtd
 * @property int $employee_number_invoices_tdy
 * @property int $employee_number_invoices_lm
 * @property int $employee_number_invoices_lw
 * @property int $employee_number_invoices_ld
 * @property int $employee_number_invoices_1y_ly
 * @property int $employee_number_invoices_1q_ly
 * @property int $employee_number_invoices_1m_ly
 * @property int $employee_number_invoices_1w_ly
 * @property int $employee_number_invoices_3d_ly
 * @property int $employee_number_invoices_ytd_ly
 * @property int $employee_number_invoices_qtd_ly
 * @property int $employee_number_invoices_mtd_ly
 * @property int $employee_number_invoices_wtd_ly
 * @property int $employee_number_invoices_tdy_ly
 * @property int $employee_number_invoices_lm_ly
 * @property int $employee_number_invoices_lw_ly
 * @property int $employee_number_invoices_ld_ly
 * @property int $employee_number_invoices_py1
 * @property int $employee_number_invoices_py2
 * @property int $employee_number_invoices_py3
 * @property int $employee_number_invoices_py4
 * @property int $employee_number_invoices_py5
 * @property int $employee_number_invoices_pq1
 * @property int $employee_number_invoices_pq2
 * @property int $employee_number_invoices_pq3
 * @property int $employee_number_invoices_pq4
 * @property int $employee_number_invoices_pq5
 * @property int $employee_number_customers_all
 * @property int $employee_number_customers_1y
 * @property int $employee_number_customers_1q
 * @property int $employee_number_customers_1m
 * @property int $employee_number_customers_1w
 * @property int $employee_number_customers_3d
 * @property int $employee_number_customers_ytd
 * @property int $employee_number_customers_qtd
 * @property int $employee_number_customers_mtd
 * @property int $employee_number_customers_wtd
 * @property int $employee_number_customers_tdy
 * @property int $employee_number_customers_lm
 * @property int $employee_number_customers_lw
 * @property int $employee_number_customers_ld
 * @property int $employee_number_customers_1y_ly
 * @property int $employee_number_customers_1q_ly
 * @property int $employee_number_customers_1m_ly
 * @property int $employee_number_customers_1w_ly
 * @property int $employee_number_customers_3d_ly
 * @property int $employee_number_customers_ytd_ly
 * @property int $employee_number_customers_qtd_ly
 * @property int $employee_number_customers_mtd_ly
 * @property int $employee_number_customers_wtd_ly
 * @property int $employee_number_customers_tdy_ly
 * @property int $employee_number_customers_lm_ly
 * @property int $employee_number_customers_lw_ly
 * @property int $employee_number_customers_ld_ly
 * @property int $employee_number_customers_py1
 * @property int $employee_number_customers_py2
 * @property int $employee_number_customers_py3
 * @property int $employee_number_customers_py4
 * @property int $employee_number_customers_py5
 * @property int $employee_number_customers_pq1
 * @property int $employee_number_customers_pq2
 * @property int $employee_number_customers_pq3
 * @property int $employee_number_customers_pq4
 * @property int $employee_number_customers_pq5
 * @property string $revenue_vip_grp_currency_all
 * @property string $revenue_vip_grp_currency_1y
 * @property string $revenue_vip_grp_currency_1q
 * @property string $revenue_vip_grp_currency_1m
 * @property string $revenue_vip_grp_currency_1w
 * @property string $revenue_vip_grp_currency_3d
 * @property string $revenue_vip_grp_currency_ytd
 * @property string $revenue_vip_grp_currency_qtd
 * @property string $revenue_vip_grp_currency_mtd
 * @property string $revenue_vip_grp_currency_wtd
 * @property string $revenue_vip_grp_currency_tdy
 * @property string $revenue_vip_grp_currency_lm
 * @property string $revenue_vip_grp_currency_lw
 * @property string $revenue_vip_grp_currency_ld
 * @property string $revenue_vip_grp_currency_1y_ly
 * @property string $revenue_vip_grp_currency_1q_ly
 * @property string $revenue_vip_grp_currency_1m_ly
 * @property string $revenue_vip_grp_currency_1w_ly
 * @property string $revenue_vip_grp_currency_3d_ly
 * @property string $revenue_vip_grp_currency_ytd_ly
 * @property string $revenue_vip_grp_currency_qtd_ly
 * @property string $revenue_vip_grp_currency_mtd_ly
 * @property string $revenue_vip_grp_currency_wtd_ly
 * @property string $revenue_vip_grp_currency_tdy_ly
 * @property string $revenue_vip_grp_currency_lm_ly
 * @property string $revenue_vip_grp_currency_lw_ly
 * @property string $revenue_vip_grp_currency_ld_ly
 * @property string $revenue_vip_grp_currency_py1
 * @property string $revenue_vip_grp_currency_py2
 * @property string $revenue_vip_grp_currency_py3
 * @property string $revenue_vip_grp_currency_py4
 * @property string $revenue_vip_grp_currency_py5
 * @property string $revenue_vip_grp_currency_pq1
 * @property string $revenue_vip_grp_currency_pq2
 * @property string $revenue_vip_grp_currency_pq3
 * @property string $revenue_vip_grp_currency_pq4
 * @property string $revenue_vip_grp_currency_pq5
 * @property string $profit_vip_grp_currency_all
 * @property string $profit_vip_grp_currency_1y
 * @property string $profit_vip_grp_currency_1q
 * @property string $profit_vip_grp_currency_1m
 * @property string $profit_vip_grp_currency_1w
 * @property string $profit_vip_grp_currency_3d
 * @property string $profit_vip_grp_currency_ytd
 * @property string $profit_vip_grp_currency_qtd
 * @property string $profit_vip_grp_currency_mtd
 * @property string $profit_vip_grp_currency_wtd
 * @property string $profit_vip_grp_currency_tdy
 * @property string $profit_vip_grp_currency_lm
 * @property string $profit_vip_grp_currency_lw
 * @property string $profit_vip_grp_currency_ld
 * @property string $profit_vip_grp_currency_1y_ly
 * @property string $profit_vip_grp_currency_1q_ly
 * @property string $profit_vip_grp_currency_1m_ly
 * @property string $profit_vip_grp_currency_1w_ly
 * @property string $profit_vip_grp_currency_3d_ly
 * @property string $profit_vip_grp_currency_ytd_ly
 * @property string $profit_vip_grp_currency_qtd_ly
 * @property string $profit_vip_grp_currency_mtd_ly
 * @property string $profit_vip_grp_currency_wtd_ly
 * @property string $profit_vip_grp_currency_tdy_ly
 * @property string $profit_vip_grp_currency_lm_ly
 * @property string $profit_vip_grp_currency_lw_ly
 * @property string $profit_vip_grp_currency_ld_ly
 * @property string $profit_vip_grp_currency_py1
 * @property string $profit_vip_grp_currency_py2
 * @property string $profit_vip_grp_currency_py3
 * @property string $profit_vip_grp_currency_py4
 * @property string $profit_vip_grp_currency_py5
 * @property string $profit_vip_grp_currency_pq1
 * @property string $profit_vip_grp_currency_pq2
 * @property string $profit_vip_grp_currency_pq3
 * @property string $profit_vip_grp_currency_pq4
 * @property string $profit_vip_grp_currency_pq5
 * @property string|null $revenue_vip_data_all
 * @property string|null $revenue_vip_data_1y
 * @property string|null $revenue_vip_data_1q
 * @property string|null $revenue_vip_data_1m
 * @property string|null $revenue_vip_data_1w
 * @property string|null $revenue_vip_data_3d
 * @property string|null $revenue_vip_data_ytd
 * @property string|null $revenue_vip_data_qtd
 * @property string|null $revenue_vip_data_mtd
 * @property string|null $revenue_vip_data_wtd
 * @property string|null $revenue_vip_data_tdy
 * @property string|null $revenue_vip_data_lm
 * @property string|null $revenue_vip_data_lw
 * @property string|null $revenue_vip_data_ld
 * @property string|null $revenue_vip_data_1y_ly
 * @property string|null $revenue_vip_data_1q_ly
 * @property string|null $revenue_vip_data_1m_ly
 * @property string|null $revenue_vip_data_1w_ly
 * @property string|null $revenue_vip_data_3d_ly
 * @property string|null $revenue_vip_data_ytd_ly
 * @property string|null $revenue_vip_data_qtd_ly
 * @property string|null $revenue_vip_data_mtd_ly
 * @property string|null $revenue_vip_data_wtd_ly
 * @property string|null $revenue_vip_data_tdy_ly
 * @property string|null $revenue_vip_data_lm_ly
 * @property string|null $revenue_vip_data_lw_ly
 * @property string|null $revenue_vip_data_ld_ly
 * @property string|null $revenue_vip_data_py1
 * @property string|null $revenue_vip_data_py2
 * @property string|null $revenue_vip_data_py3
 * @property string|null $revenue_vip_data_py4
 * @property string|null $revenue_vip_data_py5
 * @property string|null $revenue_vip_data_pq1
 * @property string|null $revenue_vip_data_pq2
 * @property string|null $revenue_vip_data_pq3
 * @property string|null $revenue_vip_data_pq4
 * @property string|null $revenue_vip_data_pq5
 * @property int $vip_number_invoices_all
 * @property int $vip_number_invoices_1y
 * @property int $vip_number_invoices_1q
 * @property int $vip_number_invoices_1m
 * @property int $vip_number_invoices_1w
 * @property int $vip_number_invoices_3d
 * @property int $vip_number_invoices_ytd
 * @property int $vip_number_invoices_qtd
 * @property int $vip_number_invoices_mtd
 * @property int $vip_number_invoices_wtd
 * @property int $vip_number_invoices_tdy
 * @property int $vip_number_invoices_lm
 * @property int $vip_number_invoices_lw
 * @property int $vip_number_invoices_ld
 * @property int $vip_number_invoices_1y_ly
 * @property int $vip_number_invoices_1q_ly
 * @property int $vip_number_invoices_1m_ly
 * @property int $vip_number_invoices_1w_ly
 * @property int $vip_number_invoices_3d_ly
 * @property int $vip_number_invoices_ytd_ly
 * @property int $vip_number_invoices_qtd_ly
 * @property int $vip_number_invoices_mtd_ly
 * @property int $vip_number_invoices_wtd_ly
 * @property int $vip_number_invoices_tdy_ly
 * @property int $vip_number_invoices_lm_ly
 * @property int $vip_number_invoices_lw_ly
 * @property int $vip_number_invoices_ld_ly
 * @property int $vip_number_invoices_py1
 * @property int $vip_number_invoices_py2
 * @property int $vip_number_invoices_py3
 * @property int $vip_number_invoices_py4
 * @property int $vip_number_invoices_py5
 * @property int $vip_number_invoices_pq1
 * @property int $vip_number_invoices_pq2
 * @property int $vip_number_invoices_pq3
 * @property int $vip_number_invoices_pq4
 * @property int $vip_number_invoices_pq5
 * @property int $vip_number_customers_all
 * @property int $vip_number_customers_1y
 * @property int $vip_number_customers_1q
 * @property int $vip_number_customers_1m
 * @property int $vip_number_customers_1w
 * @property int $vip_number_customers_3d
 * @property int $vip_number_customers_ytd
 * @property int $vip_number_customers_qtd
 * @property int $vip_number_customers_mtd
 * @property int $vip_number_customers_wtd
 * @property int $vip_number_customers_tdy
 * @property int $vip_number_customers_lm
 * @property int $vip_number_customers_lw
 * @property int $vip_number_customers_ld
 * @property int $vip_number_customers_1y_ly
 * @property int $vip_number_customers_1q_ly
 * @property int $vip_number_customers_1m_ly
 * @property int $vip_number_customers_1w_ly
 * @property int $vip_number_customers_3d_ly
 * @property int $vip_number_customers_ytd_ly
 * @property int $vip_number_customers_qtd_ly
 * @property int $vip_number_customers_mtd_ly
 * @property int $vip_number_customers_wtd_ly
 * @property int $vip_number_customers_tdy_ly
 * @property int $vip_number_customers_lm_ly
 * @property int $vip_number_customers_lw_ly
 * @property int $vip_number_customers_ld_ly
 * @property int $vip_number_customers_py1
 * @property int $vip_number_customers_py2
 * @property int $vip_number_customers_py3
 * @property int $vip_number_customers_py4
 * @property int $vip_number_customers_py5
 * @property int $vip_number_customers_pq1
 * @property int $vip_number_customers_pq2
 * @property int $vip_number_customers_pq3
 * @property int $vip_number_customers_pq4
 * @property int $vip_number_customers_pq5
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read Stock $stock
 * @method static \Illuminate\Database\Eloquent\Builder<static>|StockSalesInterval newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|StockSalesInterval newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|StockSalesInterval query()
 * @mixin \Eloquent
 */
class StockSalesInterval extends Model
{
    protected $table = 'stock_sales_intervals';

    protected $guarded = [];


    public function stock(): BelongsTo
    {
        return $this->belongsTo(Stock::class);
    }
}
